### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by frankysan** [BSData/dusttactics#13]
I want to be able to contribute to this file. Especially now when the new stat cards are coming soon, and players will want to have up to date files.

**Comment by amis92** [comment]
Hello, @frankysan. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!

**Comment by reyzambo** [comment]
Tnx amis92, welcome frankysan! 

I need help for insert all crews then welcome! Contact me if you have trouble or need info about add the data file. But first of if you can test the game system if is complete or if I miss somethings, this is a good help, then you may work on do you want.

Ps: I have a little rule, I don't write the complete stat card but only the base reference, no rule no actions, only FAQ models and rules avaiable on wyrd download sections, I think is a good rule for respect on this game ;)
